core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from core import views


app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signin', views.SignInView.as_view(), name='signin'),
    path('logout', LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gitlab_sign_in_oauth/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

core/models.py
import json
import requests

from django.db import models
from django.conf import settings

import jsonfield


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    profile_url = models.URLField(blank=True, null=True)
    avatar_url = models.URLField(blank=True, null=True)
    suid = models.CharField(max_length=256, blank=True, null=True)
    location = models.CharField(max_length=256, blank=True, null=True)
    projects_json = jsonfield.JSONField()

    def __str__(self):
        return f'{self.user}'

    # I did not stick to creating separetad entity for repositories
    # So fetching user's repositories is implemented by this method
    # Returns a JSON of projects/repositories and saves it to JSONField 
    def get_projects(self, token):        
        projects = requests.get(f'https://gitlab.com/api/v4/users/{self.suid}/projects',
            headers={'Authorization': f'Bearer {token}'}).json()
        # print(projects)
        self.projects_json = projects
        self.save()
        return projects

core/views.py
import json
import requests

from django.shortcuts import render
from django.views import View
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.conf import settings

from core.models import Profile


class SignInView(SuccessMessageMixin, LoginView):
    template_name = 'signin.html'
    redirect_authenticated_user = True
    success_message = "You logged in successfuly"

class HomeView(View):
    template_name = 'index.html'
    
    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request, self.template_name, ctx)
    

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GitLab OAuth Task{% endblock title %}</title>
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

    <!-- Overhang(Notifications) -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/overhang.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/overhang.min.js' %}"></script>

</head>

<body>
    <!-- Navbar -->
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="#">
               <h1 class='has-text-weight-bold'><a href="{% url 'core:home' %}">GitLab OAuth Task</a></h1>
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu"
                aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if request.user.is_anonymous %}
                            <a class="button is-success" href='{% url "core:signin" %}'>
                                Sign in
                            </a>
                        {% else %}
                            <p class='mr-5'>Hello, {{ request.user }} !</p>
                        
                            <a class="button is-info" href='{% url "core:logout" %}?next={% url "core:home" %}'>
                                Logout
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- /Navbar -->

    {% block content %}
    {% endblock content %}

    <script>
        {% if messages %}
            {% for message in messages %}        

                $("body").overhang({
                type: "{{ message.tags }}",
                message: "{{ message }}",
                closeConfirm: true,
                });

            {% endfor %}
        {% endif %}

    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        {% if request.user.is_anonymous %}
        <p class='has-bold-text has-center-text'>To see user's profile and active repositories - Sign In, please.</p>
        {% else %}
        <div>    
            <p class='mr-5'>Hello, <a href="{{ request.user.profile.profile_url }}">{{ request.user }}</a> !</p>
            <img src="{{ request.user.profile.avatar_url }}" alt="{{ request.user}}">

            <hr>
            <p>Repositories</p>
            
            {% for rep in request.user.profile.projects_json %}
                <a href="{{ rep.web_url }}">
                    <p>{{ forloop.counter}} - [Rep ID: {{ rep.id }}] - {{ rep.name}}</p>
                </a>
            {% empty %}
                <p>No Repositories ):</p>
            {% endfor %}
        </div>


    {% endif %}
    </div>
{% endblock content %}

templates/signin.html
{% extends 'base.html' %}
{% block title %}Sign In{% endblock title %}

{% block content %}
<div class="container">
    <div class="has-text-centered">
        <h4 class='has-text-weight-bold'>Sign In</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class='button is-success' type="submit">Sign In</button>
        </form>
            <p><strong>-- or --</strong></p>
            <a href="{% url 'social:begin' 'gitlab' %}">Login with GitLab</a><br>
    </div>
</div>
{% endblock %}